### ISSUE TITLE
SX_decon 具体实现

### ISSUE THREAD

**Issue by JouSF-1409** [georom1996/GCSRF_GIG_USTC-Training-Package#2]
非常好的分享，还在看section 1的代码。

几个地震学的问题：

1. Yang 2006 的Synthetic 结果中，S波接收函数作动校正(moveout correction)的改善很好。想知道这里作动校正的spmove.joe 具体是怎样的算法，依照什么模型，什么条件做的动校正。动校正这块说的很多，但我看到的代码很少。做动校正是否就是 将记录转化到零炮检距( p = 0 )记录。他与ccp叠加的关系几何？ 
2. 继续ccp叠加的问题，ccp叠加的核心是对Ps波转换点在空间上的还原。那么对于面状的台站，我应该作动校正吗，还是先叠加到3D网格中，再切出一个剖面进行观察。

几个代码风格上的问题：
1. SX_decon为什么要反复作rot 2 gcp的过程，既然每次都从头段中提取一个baz，那么直接将数据保存为rtz分量，然后对P-SV面旋转？可能这也比较符合我们平时做的流程，也节省计算时间。而且这个旋转，在GC_SRF.cpp里还是定长的，是否能做一些改进，比如说二分，用一个阈值和最低的精度（1度的上限而不是4度的步长，还有一个归一化的阈值）去作旋转。taup 同样能算出一个入射角，以此为基础也同样能加速这个过程？
3. spike_t1,t2的时间窗怎么给出。我想这可能是整个程序中最不自动化的一个部分。这个问题等价于怎么认识SKS波在～85度范围内的干扰，如果给的时间窗太长，把常见的干扰震相，比如说SKS之于S，S 之于ScS 也放进了时间窗，或者说截取了部分，肯定是很麻烦的。在kumar的这个案例中，S与SKS波的叠加还是很明显的（S波晚于SKS波4s，但振幅显著更强），但如果S振幅与SKS波相近，那很自然会带来不必要的麻烦。
4. get_spikefilter 这个函数不是很理解。在GC_SRF.cpp和SX_Deconv.cpp两个文件中都定义了。但是！在以t0为判断标准的 if 之前，定义了t0==2 ?然后还对t0做分支判断？是已经屏蔽掉的接口？
5. SX_Deconv.cpp中还计算了max并保存到user6里，好习惯，但sac读写一遍后会保存到depmax 变量中，或者直接写到那里面？

更多的还在看，不过我水平不行，读得很慢。

**Comment by georom1996** [comment]
感谢您的问题，我尝试做出回应，欢迎一起讨论，共同进步。

**几个地震学的问题：**

1. Yang 2006 的Synthetic 结果中，S波接收函数作动校正(moveout correction)的改善很好。想知道这里作动校正的spmove.joe 具体是怎样的算法，依照什么模型，什么条件做的动校正。动校正这块说的很多，但我看到的代码很少。做动校正是否就是 将记录转化到零炮检距( p = 0 )记录。他与ccp叠加的关系几何？
**问题回应1：**
	动校正的具体算法与Ps转换波的算法类似，本质是上根据Sp转换波的到时对波形进行一定伸展，使得波形伸展为需要的或者设置的慢度或震中距。如果看Xiaohui Yuan教授的原始代码，不论是P波接收函数的moveout correction，还是S波接收函数的moveout correction，  首先都会读取sac文件的 gcarc头变量，程序中使用这一变量在两个固定的数组中寻找其射线参数所在区间， 其中的 x 数组为震中距的等间隔排列， y 数组是每个震中距对应射线参数的排列，使用Taup计算可以发现y数组与震源深度25km时对应的S震相射线参数相似。后续的程序中，他们直接使用线性插值计算文件震中距对应的射线参数，然后基于Iasp91。dat模型计算不同深度震相的到时，然后估算每一个数据点的平移量，对所有平移后的数据点按照原始文件采样率做一次重采样，就得到了最终的输出波形。如果这一步校正到0偏移距，则后续在PSDM程序包提供的CCP叠加中可以关闭震中距校正的选项；如果这一步并未校正，则在程序包中需要考虑开启震中距校正的选项。但是前提是需要在PSDM中确保校正使用的射线文件合乎PSDM程序规范的同时能够对SRF进行正确的校正（PSDM的这个功能点我个人目前存疑，且其不是我此前工作的要点，所以在案例准备时没有考虑其具体的功能）。

2. 继续ccp叠加的问题，ccp叠加的核心是对Ps波转换点在空间上的还原。那么对于面状的台站，我应该作动校正吗，还是先叠加到3D网格中，再切出一个剖面进行观察。
**问题回应2：**
	不论是线状台还是面状台，我个人认为最理想的都是不做动校正，在3D的速度网格中通过射线追踪进行校正，最终叠加或偏移。但是如果需要进行单台分析的时候，则建议动校正之前分析震相的时距特性，动校正之后分析特定震相的振幅相位特征。

**几个代码风格上的问题：**

1.  SX_decon为什么要反复作rot 2 gcp的过程，既然每次都从头段中提取一个baz，那么直接将数据保存为rtz分量，然后对P-SV面旋转？可能这也比较符合我们平时做的流程，也节省计算时间。而且这个旋转，在GC_SRF。cpp里还是定长的，是否能做一些改进，比如说二分，用一个阈值和最低的精度（1度的上限而不是4度的步长，还有一个归一化的阈值）去作旋转。taup 同样能算出一个入射角，以此为基础也同样能加速这个过程？
**代码风格回应1：**
	代码的混乱，我向您表示抱歉。因为这个工作横跨了我整个博士研究阶段，这一部分的Bash shell脚本最早大概是在2020年完成，当时对脚本语言的理解只停留在能跑就行的阶段，并未考虑效率问题。同时，SX_Deconv部分的案例不是为了实际使用，单纯为了复现Kumar的结果，所以所提到的旋转角度和间隔完全与其文章一致，但是这些均可以在GC_SRF源码中修改实现。当然旋转间隔越小，计算代价将越高。但是，这一部分基础计算的算法我已经在python下完整实现了，只是满足共享上线的要求还需要一些时间。Taup确实可以计算入射角，但是理论角度与实际观测的偏振还是会有差异，这种差异难以用均匀的速度模型进行刻画和表征，所以我依然不建议直接使用或者只理论计算的入射角，波形的偏振相比来说应该更符合Ground Truth。我个人一般会用Taup的角度旋转了计算，同时也用旋转反褶积做一下，一般还会检查一下波形的极化，多做一点方便自己工作里面进行逐步检查。

2.  spike_t1，t2的时间窗怎么给出。我想这可能是整个程序中最不自动化的一个部分。这个问题等价于怎么认识SKS波在～85度范围内的干扰，如果给的时间窗太长，把常见的干扰震相，比如说SKS之于S，S 之于ScS 也放进了时间窗，或者说截取了部分，肯定是很麻烦的。在kumar的这个案例中，S与SKS波的叠加还是很明显的（S波晚于SKS波4s，但振幅显著更强），但如果S振幅与SKS波相近，那很自然会带来不必要的麻烦。
**代码风格回应2：**
	t1 和t2在GC_SRF中是通过循环去实现的，由于低通滤波到了4s，所以我设定的t1一般是-5s，这个也可以根据实际情况修改。在GC_SRF+GC_SRF_post程序组合计算后，可以确定win_len和inci_ang，其中的win_len确定的就是t2。

3. get_spikefilter 这个函数不是很理解。在GC_SRF.cpp和SX_Deconv.cpp两个文件中都定义了。但是！在以t0为判断标准的 if 之前，定义了t0\==2 ?然后还对t0做分支判断？是已经屏蔽掉的接口？
**代码风格回应3：**
	get_spikefilter 函数提取了原始波形上的一段时窗波形作为子波w，然后利用这个子波w和单位脉冲信号d构建方程组w i =d，求解得到的i就是所谓的逆子波滤波器，这个滤波器的作用就是压制形态类似w的子波使其变为类似d的脉冲信号，用这样的逆子波滤波器卷积原始分量波形就可以得到对应的反褶积结果。感谢您看的这么仔细，原始代码在Seismic Handler (SH)程序包中可以找到，他们早期的程序使用指针位移的方式提供了三种不同的t0选择方式，但是依据我和部分使用SH计算SRF的学者沟通后保留了他们均使用的t0\==2方式，目测在数学上可能对应于计算波形质心位置来定位子波的起算点。为方便使用，我把其他的方式保留但是屏蔽了，正是有待类似您这样有兴趣一起讨论的同行来发现并尝试落实这个问题。

4. SX_Deconv.cpp中还计算了max并保存到user6里，好习惯，但sac读写一遍后会保存到depmax 变量中，或者直接写到那里面？
**代码风格回应4：**
	这个max是我早期测试时候为了方便自己检查归一化波形和未归一化波形的差异时保存的，当时想的是可能面对需要从归一化波形返回未归一化波形的使用情形。但是后续的工作中我个人并未实际用到，只是还保留在老代码中。
